# Generated by Django 3.2.3 on 2021-05-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatweoffer',
            name='brief_overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='overview',
            field=models.TextField(),
        ),
    ]
