# Generated by Django 3.2.3 on 2021-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_auto_20210520_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatweoffer',
            name='brief_overview',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='overview',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='whatweoffer',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
