# Generated by Django 3.2.3 on 2021-05-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_signup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='password',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='retype_password',
        ),
    ]
