# Generated by Django 3.2.3 on 2021-05-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_auto_20210525_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='overview_of_section',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_image',
            field=models.ImageField(default=1, upload_to='teacher_pics'),
            preserve_default=False,
        ),
    ]
