# Generated by Django 3.2.3 on 2021-06-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0009_rename_blog_ttle_blog_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_detail',
            field=models.TextField(max_length=250),
        ),
    ]
