# Generated by Django 3.2.3 on 2021-06-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
